'''
系统错误代码

此模块实现相应`CPython`模块的子集，如下所述。

有关更多信息，请参阅原始`CPython`文档：[errno](https://docs.python.org/3.5/library/errno.html#module-errno)。

此模块提供对`OSError`异常的符号错误代码的访问。

特定的代码清单取决于 MicroPython 端口。

[查看文档](https://docs.micropython.org/en/latest/library/errno.html)
'''
# Constants
errorcode: dict = ...
'''将数字错误代码映射到具有符号错误代码字符串的字典。'''

# Error codes, based on ANSI C/POSIX standard.
# All error codes start with "E".
# As mentioned above, inventory of the codes depends on MicroPython port.
# Errors are usually accessible as `exc.errno` where `exc` is an instance of
# `OSError`. 
EPERM: int = ...
ENOENT: int = ...
EIO: int = ...
EBADF: int = ...
EAGAIN: int = ...
ENOMEM: int = ...
EACCES: int = ...
EEXIST: int = ...
ENODEV: int = ...
EISDIR: int = ...
EINVAL: int = ...
EOPNOTSUPP: int = ...
EADDRINUSE: int = ...
ECONNABORTED: int = ...
ECONNRESET: int = ...
ENOBUFS: int = ...
ENOTCONN: int = ...
ETIMEDOUT: int = ...
ECONNREFUSED: int = ...
EHOSTUNREACH: int = ...
EALREADY: int = ...
EINPROGRESS: int = ...
