'''
system error codes

This module implements a subset of the corresponding CPython module, as described below.

For more information, refer to the original CPython documentation: errno.

This module provides access to symbolic error codes for `OSError` exception.

A particular inventory of codes depends on MicroPython port.

[View Doc](https://docs.micropython.org/en/latest/library/errno.html)
'''
# Constants
# Dictionary mapping numeric error codes to strings with symbolic error code.
errorcode = ...

'''
Error codes, based on ANSI C/POSIX standard.

All error codes start with "E".

As mentioned above, inventory of the codes depends on MicroPython port.

Errors are usually accessible as `exc.errno` where `exc` is an instance of `OSError`. 
'''
EPERM = ...
ENOENT = ...
EIO = ...
EBADF = ...
EAGAIN = ...
ENOMEM = ...
EACCES = ...
EEXIST = ...
ENODEV = ...
EISDIR = ...
EINVAL = ...
EOPNOTSUPP = ...
EADDRINUSE = ...
ECONNABORTED = ...
ECONNRESET = ...
ENOBUFS = ...
ENOTCONN = ...
ETIMEDOUT = ...
ECONNREFUSED = ...
EHOSTUNREACH = ...
EALREADY = ...
EINPROGRESS = ...
